from flask import Blueprint, send_file, jsonify
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import io
import json
from datetime import datetime
from models import Prediction
from routes.auth_routes import token_required

report_bp = Blueprint("report_bp", __name__)


@report_bp.route("/api/predict/report/<int:prediction_id>", methods=["GET"])
@token_required
def generate_report(prediction_id):

    prediction = Prediction.query.get(prediction_id)

    if not prediction:
        return jsonify({"error": "Prediction not found"}), 404

    # SECURITY CHECK: Only the owner can download their report
    if prediction.user_id != request.user.id:
        return jsonify({"error": "Unauthorized"}), 403

    # Convert input JSON to dict
    inputs = json.loads(prediction.input_data)

    # Create PDF buffer
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(1 * inch, height - 1 * inch, "GBS Clinical Prediction Report")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(1 * inch, height - 1.3 * inch, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Prediction Results Section
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(1 * inch, height - 2 * inch, "Prediction Result")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(1 * inch, height - 2.4 * inch, f"Predicted Subtype: {prediction.predicted_subtype}")
    pdf.drawString(1 * inch, height - 2.7 * inch, f"Confidence: {round(prediction.confidence * 100, 2)}%")

    # Patient Inputs
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(1 * inch, height - 3.3 * inch, "Patient Clinical Data")

    y = height - 3.7 * inch
    pdf.setFont("Helvetica", 12)

    for key, value in inputs.items():
        pdf.drawString(1 * inch, y, f"{key.replace('_', ' ').title()}: {value}")
        y -= 0.25 * inch

        if y < 1 * inch:  # New page
            pdf.showPage()
            y = height - 1 * inch

    # Footer
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(1 * inch, 0.7 * inch, "This report was automatically generated by the NeuroDiagnose AI System.")

    pdf.save()
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"gbs_report_{prediction_id}.pdf",
        mimetype="application/pdf"
    )
